name: dart_i2p
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://git.mrcyjanek.net/p3pch4t/dart_i2p
publish_to: https://git.mrcyjanek.net/api/packages/p3pch4t/pub

environment:
  sdk: ^3.1.1

dependencies:
  base32: 2.1.3
  crypto: 3.0.3
  dio: 5.3.2
  html: 0.15.4
  http: 1.1.0
  path: 1.8.3

dev_dependencies:
  lints: 3.0.0
  test: 1.21.0
