#!/bin/bash

# All this script does is generate the gen_certs.g.dart
# file that I commit onto the repo for the DX sake.

set -e
cd $(dirname $0)
WD="$(pwd)"

cd $(mktemp -d)

git clone https://github.com/PurpleI2P/i2pd --recursive
cd i2pd/contrib/certificates
echo "// Autogenerated"> $WD/gen_certs.g.dart
echo "// $(uname -a)">> $WD/gen_certs.g.dart
echo "// $(date)">> $WD/gen_certs.g.dart
for type in *;
do
    cd $type
    echo "const Map<String, String> $type = {" >> $WD/gen_certs.g.dart
    for i in *;
    do
        echo "    '$i': r'''$(cat "$i")'''," >> $WD/gen_certs.g.dart
    done    
    echo "};" >> $WD/gen_certs.g.dart
    cd ..
done